Miclael Nielsen's Neural Network

http://neuralnetworksanddeeplearning.com/chap1.html

In [1]:
import numpy as np

In [62]:
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

def sigmoid_prime(z):
    return sigmoid(z)*(1-sigmoid(z))

In [61]:
class Network(object):
    
    def __init__(self, layer_sizes):
        self.num_layers = len(layer_sizes)
        self.layer_sizes = layer_sizes
        
        self.biases  = [np.random.randn(l, 1) for l in layer_sizes[1:]]
        self.weights = [np.random.randn(dest, source) 
                        for (source, dest) in zip(layer_sizes[:-1], layer_sizes[1:])]
        
    def feedforward(self, inp):
        for b, w in zip(self.biases, self.weights):
            inp = sigmoid(np.dot(w, inp) + b)
        return inp
        
    def SGD(self, x, y, epochs, batch_size, learning_rate):
        n = len(x) # num instances
        num_batches = n // batch_size
        
        for e in range(epochs):
            for b in range(num_batches):
                mask = np.random.randint(0, n, batch_size)
                x_batch = x[mask, :]
                y_batch = y[mask]
                
                self.update_mini_batch(x_batch, y_batch, learning_rate)
                
            print("Epoch {0} completed".format(e))

    def update_mini_batch(self, x_batch, y_batch, learning_rate):
        n = len(x_batch)
        grads_b = [np.zeros(b.shape) for b in self.biases]
        grads_w = [np.zeros(w.shape) for w in self.weights]
        
        for x, y in zip(x_batch, y_batch):
            delta_b, delta_w = self.backprop(x, y)
            grads_b = [g + d for g, d in zip(grads_b, delta_b)]
            grads_w = [g + d for g, d in zip(grads_w, delta_w)]
            
        self.weights = [w - (learning_rate/n) * gw for w, gw in zip(self.weights, grads_w)]
        self.biases  = [b - (learning_rate/n) * gb for b, gb in zip(self.biases, grads_b)]
        
    def backprop(self, x, y):
        delta_b = [np.zeros(b.shape) for b in self.biases]
        delta_w = [np.zeros(w.shape) for w in self.weights]
        
        # forward pass
        activation = x
        activations = [x]
        zs = []
        for w, b in zip(self.weights, self.biases):
            z = np.dot(w, activation) + b
            zs.append(z)
            activation = sigmoid(z)
            activations.append(activation)
        
        # backward pass
        delta = self.cost_derivative(activations[-1], y) * sigmoid_prime(zs[-1])
        delta_b[-1] = delta
        delta_w[-1] = np.dot(delta, activations[-2].transpose())
        
        for l in range(2, self.num_layers):
            z = zs[-l]
            sp = sigmoid_prime(z)
            
            

    def cost_derivative(self, output_activations, y):
        return (output_activations - y)

In [56]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [60]:
n = np.random.randint(0, 10, 2)
x[n]

array([2, 1])

In [24]:
net = Network([2, 4, 3])

In [27]:
inp = np.array([1, 2]).reshape(-1, 1)
print(inp)
net.feedforward(inp)

[[1]
 [2]]
(4, 2) (2, 1)
(3, 4) (4, 1)


array([[ 0.78967759],
       [ 0.16309279],
       [ 0.11039694]])